# Azaria Wiki - Docker Compose Configuration
version: '3.8'

services:
  azaria-wiki:
    image: ghcr.io/Hlofiys/azaria-wiki:latest
    container_name: azaria-wiki
    restart: unless-stopped
    
    # Port mapping
    ports:
      - "8080:8080"
    
    # Environment variables
    environment:
      - NODE_ENV=production
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem for security
    read_only: true
    
    # Temporary filesystems for nginx
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/run:noexec,nosuid,size=50m
      - /tmp:noexec,nosuid,size=50m
    
    # Labels for better organization
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.azaria-wiki.rule=Host(`azaria.local`)"
      - "traefik.http.services.azaria-wiki.loadbalancer.server.port=8080"
      - "com.azaria.wiki.description=Azaria Wiki - Medieval-Dep-Punk Universe"
      - "com.azaria.wiki.version=0.0.1"