# Azaria Wiki - Docker Compose Configuration

services:
  azaria-wiki:
    image: ghcr.io/hlofiys/azaria-wiki:latest
    container_name: azaria-wiki
    restart: unless-stopped

    # Port mapping
    ports:
      - '8080:8080'

    # Environment variables
    environment:
      - NODE_ENV=production

    # Health check
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
