# Azaria Wiki - Docker Compose Configuration
version: '3.8'

services:
  azaria-wiki:
    image: ghcr.io/hlofiys/azaria-wiki:latest
    container_name: azaria-wiki
    restart: unless-stopped
    
    # Port mapping
    ports:
      - "8080:8080"
    
    # Environment variables
    environment:
      - NODE_ENV=production
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s