backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "characters"
    label: "Персонажи"
    folder: "src/lib/lore-content/characters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Категория", name: "category", widget: "hidden", default: "characters" }
      - { label: "Фракция", name: "faction", widget: "string", required: false }
      - { label: "Статус", name: "status", widget: "select", options: ["Alive", "Deceased", "Unknown"], required: false }
      - { label: "Возраст", name: "age", widget: "number", required: false }
      - { label: "Тип", name: "type", widget: "string", required: false }
      - { label: "Изображение", name: "image", widget: "image", required: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Содержание", name: "body", widget: "markdown" }

  - name: "locations"
    label: "Локации"
    folder: "src/lib/lore-content/locations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Категория", name: "category", widget: "hidden", default: "locations" }
      - { label: "Тип", name: "type", widget: "string", required: false }
      - { label: "Фракция", name: "faction", widget: "string", required: false }
      - { label: "Правитель", name: "ruler", widget: "string", required: false }
      - { label: "Население", name: "population", widget: "string", required: false }
      - { label: "Протяженность", name: "length", widget: "string", required: false }
      - { label: "Изображение", name: "image", widget: "image", required: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Содержание", name: "body", widget: "markdown" }

  - name: "factions"
    label: "Фракции"
    folder: "src/lib/lore-content/factions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Категория", name: "category", widget: "hidden", default: "factions" }
      - { label: "Тип", name: "type", widget: "string", required: false }
      - { label: "Правитель", name: "ruler", widget: "string", required: false }
      - { label: "Население", name: "population", widget: "string", required: false }
      - { label: "Специализация", name: "specialization", widget: "string", required: false }
      - { label: "Философия", name: "philosophy", widget: "string", required: false }
      - { label: "Доступ", name: "access", widget: "string", required: false }
      - { label: "Члены", name: "members", widget: "string", required: false }
      - { label: "Изображение", name: "image", widget: "image", required: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Содержание", name: "body", widget: "markdown" }

  - name: "artifacts"
    label: "Артефакты"
    folder: "src/lib/lore-content/artifacts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Категория", name: "category", widget: "hidden", default: "artifacts" }
      - { label: "Тип", name: "type", widget: "string", required: false }
      - { label: "Владелец", name: "owner", widget: "string", required: false }
      - { label: "Эффект", name: "effect", widget: "string", required: false }
      - { label: "Изображение", name: "image", widget: "image", required: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Содержание", name: "body", widget: "markdown" }

  - name: "concepts"
    label: "Концепции"
    folder: "src/lib/lore-content/concepts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Категория", name: "category", widget: "hidden", default: "concepts" }
      - { label: "Тип", name: "type", widget: "string", required: false }
      - { label: "Описание", name: "description", widget: "string", required: false }
      - { label: "Изображение", name: "image", widget: "image", required: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Содержание", name: "body", widget: "markdown" }

  - name: "creatures"
    label: "Существа"
    folder: "src/lib/lore-content/creatures"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Категория", name: "category", widget: "hidden", default: "creatures" }
      - { label: "Тип", name: "type", widget: "string", required: false }
      - { label: "Создатель", name: "creator", widget: "string", required: false }
      - { label: "Эпоха", name: "era", widget: "string", required: false }
      - { label: "Realm", name: "realm", widget: "string", required: false }
      - { label: "Особенность", name: "feature", widget: "string", required: false }
      - { label: "Изображение", name: "image", widget: "image", required: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }
      - { label: "Содержание", name: "body", widget: "markdown" }