// Downloads Google Fonts woff2 files and generates @font-face CSS (self-hosted).
// Collapses variable fonts that Google serves as one file per weight axis.
import { mkdir, writeFile, readdir, rm } from 'node:fs/promises';

const OUT_DIR = process.argv[2] ?? 'static/fonts';
const CSS_OUT = process.argv[3] ?? 'src/lib/styles/fonts.css';
const UA =
	'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const API =
	'https://fonts.googleapis.com/css2?family=Prata&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400&family=IBM+Plex+Mono:wght@400;500;600&display=swap';

const WANTED_SUBSETS = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text();

/** @type {Map<string, {family:string,style:string,subset:string,url:string,range:string,weights:number[]}>} */
const byUrl = new Map();
/** Counts distinct files per family/style/subset so static families keep weights in the filename. */
const filesPerFamily = new Map();

for (const chunk of css.split('/*').slice(1)) {
	const subset = chunk.slice(0, chunk.indexOf('*/')).trim();
	if (!WANTED_SUBSETS.has(subset)) continue;
	const block = chunk.slice(chunk.indexOf('*/') + 2);
	const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
	const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
	const weight = Number(/font-weight:\s*(\d+)/.exec(block)?.[1]);
	const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
	const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
	if (!family || !url || !weight) continue;

	const key = `${family}|${style}|${subset}`;
	const urls = filesPerFamily.get(key) ?? new Set();
	urls.add(url);
	filesPerFamily.set(key, urls);

	const entry = byUrl.get(url) ?? { family, style, subset, url, range, weights: [] };
	entry.weights.push(weight);
	byUrl.set(url, entry);
}

// Remove previous output so stale weight-specific duplicates do not linger.
await mkdir(OUT_DIR, { recursive: true });
for (const name of await readdir(OUT_DIR)) {
	if (name.endsWith('.woff2')) await rm(`${OUT_DIR}/${name}`);
}

let out = `/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n\n`;
let count = 0;

for (const entry of byUrl.values()) {
	const min = Math.min(...entry.weights);
	const max = Math.max(...entry.weights);
	const slug = entry.family.toLowerCase().replace(/\s+/g, '-');
	const styleSlug = entry.style === 'italic' ? '-italic' : '';
	const isStaticFamily =
		(filesPerFamily.get(`${entry.family}|${entry.style}|${entry.subset}`)?.size ?? 1) > 1;
	const weightSlug = isStaticFamily ? `-${min}` : '';
	const name = `${slug}${styleSlug}${weightSlug}-${entry.subset}.woff2`;

	const res = await fetch(entry.url, { headers: { 'User-Agent': UA } });
	const buf = Buffer.from(await res.arrayBuffer());
	await writeFile(`${OUT_DIR}/${name}`, buf);
	count += 1;
	console.log(
		`  ${name.padEnd(38)} ${(buf.length / 1024).toFixed(1)} kB  ${min}${max !== min ? `–${max}` : ''}`
	);

	out += `@font-face {
	font-family: '${entry.family}';
	font-style: ${entry.style};
	font-weight: ${min}${max !== min ? ` ${max}` : ''};
	font-display: swap;
	src: url('/fonts/${name}') format('woff2');
	unicode-range: ${entry.range};
}\n\n`;
}

await mkdir(CSS_OUT.replace(/\/[^/]+$/, ''), { recursive: true });
await writeFile(CSS_OUT, out);
console.log(`\n${count} files -> ${OUT_DIR}\n@font-face css -> ${CSS_OUT}`);
