// Bakes the icons actually used in the app into a local Iconify collection,
// so nothing is fetched from the network at runtime (offline PWA friendly).
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { globSync } from 'node:fs';
import { readFileSync } from 'node:fs';

const SOURCE_GLOBS = ['src/**/*.svelte', 'src/**/*.ts'];
const OUT = 'src/lib/icons/collection.ts';

const files = SOURCE_GLOBS.flatMap((pattern) => globSync(pattern, { cwd: process.cwd() }));

const wanted = new Set();

for (const file of files) {
	const text = readFileSync(file, 'utf-8');

	for (const match of text.matchAll(/icon:\s*'([a-z0-9-]+:[a-z0-9-]+)'/g)) {
		wanted.add(match[1]);
	}
	for (const match of text.matchAll(/icon="([a-z0-9-]+:[a-z0-9-]+)"/g)) {
		wanted.add(match[1]);
	}
	for (const match of text.matchAll(/icon=\{\s*'([a-z0-9-]+:[a-z0-9-]+)'\s*\}/g)) {
		wanted.add(match[1]);
	}
}

// Resolve the uiIcons map keys used via getUIIcon('…') to real icon names.
const iconsSource = await readFile('src/lib/icons.ts', 'utf-8');
const uiMap = new Map();
for (const match of iconsSource.matchAll(
	/^\t(?:'([^']+)'|([a-z-]+)):\s*'([a-z0-9-]+:[a-z0-9-]+)'/gm
)) {
	uiMap.set(match[1] ?? match[2], match[3]);
}

// Category sigils live in the pure category module.
const categoriesSource = await readFile('src/lib/utils/categories.ts', 'utf-8');
for (const match of categoriesSource.matchAll(/'([a-z0-9-]+):([a-z0-9-]+)'/g)) {
	wanted.add(`${match[1]}:${match[2]}`);
}

for (const file of files) {
	const text = readFileSync(file, 'utf-8');
	for (const match of text.matchAll(/getUIIcon\('([a-zA-Z-]+)'\)/g)) {
		const icon = uiMap.get(match[1]);
		if (icon) wanted.add(icon);
	}
}

// Always include the bespoke ones used dynamically.
['mdi:close', 'mdi:chevron-down', 'mdi:arrow-left'].forEach((name) => wanted.add(name));

const byPrefix = new Map();
for (const name of wanted) {
	const [prefix, icon] = name.split(':');
	if (!byPrefix.has(prefix)) byPrefix.set(prefix, new Set());
	byPrefix.get(prefix).add(icon);
}

const collections = [];

for (const [prefix, names] of byPrefix) {
	const path = `node_modules/@iconify-json/${prefix}/icons.json`;
	const raw = JSON.parse(await readFile(path, 'utf-8'));

	const icons = {};
	for (const name of names) {
		if (raw.icons[name]) {
			icons[name] = raw.icons[name];
			continue;
		}
		// Follow one level of alias, e.g. mdi:refresh → mdi:refresh
		const alias = raw.aliases?.[name];
		const parent = alias?.parent;
		if (parent && raw.icons[parent]) {
			icons[name] = { ...raw.icons[parent], ...alias };
			delete icons[name].parent;
			continue;
		}
		console.warn(`  ! icon not found: ${prefix}:${name}`);
	}

	collections.push({
		prefix,
		icons,
		width: raw.width ?? 24,
		height: raw.height ?? 24
	});
	console.log(`  ${prefix}: ${Object.keys(icons).length} icons`);
}

const output = `// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
import type { IconifyJSON } from '@iconify/svelte';

export const iconCollections: IconifyJSON[] = ${JSON.stringify(collections)};
`;

await mkdir(OUT.replace(/\/[^/]+$/, ''), { recursive: true });
await writeFile(OUT, output);
console.log(`\n${wanted.size} icons -> ${OUT}`);
